server {
    listen 80;
    
    location / {
    	root /usr/share/nginx/html;
	try_files $uri $uri/ /index.html;
    }

    location /itb-mshop/v1/sale-items {
        proxy_pass http://be-container:8080/itb-mshop/v1/sale-items;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
