services:
  db:
    image: mysql
    container_name: db-container
    volumes:
      - ./database/sql-file/:/docker-entrypoint-initdb.d
      - ./database/csv-file/:/var/lib/mysql-files
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: INT221_db
      TZ: Asia/Bangkok
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      start_period: 5s

  be:
    build: ./backend
    container_name: be-container
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      db:
        condition: service_healthy

  fe:
    build:
      context: ./frontend
      dockerfile: dockerfile_Prod
    container_name: fe-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./frontend/ssl:/etc/nginx/ssl
    networks:
      - mynetwork
    depends_on:
      - be

volumes:
  mysql-data:

networks:
  mynetwork:
    driver: bridge
